version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_odd_game_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: odds_game
      MYSQL_USER: rivertech
      MYSQL_PASSWORD: sometemporarypassword#$
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
